Repository statisticsnorway/mimir, pull requests merged in 2025-06, with the labels that each got.

#3267 Release 15-06-25
  gradle.properties
  src/main/resources/lib/cipher/cipherRss.ts
  src/main/resources/lib/ssb/cron/cron.ts
  src/main/resources/lib/ssb/cron/pushRss.ts
  src/main/resources/lib/ssb/cron/updateSDDSTables.ts
  src/main/resources/lib/ssb/dashboard/dashboard.ts
  src/main/resources/lib/ssb/repo/job.ts
  src/main/resources/lib/ssb/utils/taskUtils.ts
  src/main/resources/lib/types/cookieBanner.ts
  src/main/resources/react4xp/_entries/CookieBanner.tsx
  src/main/resources/react4xp/dashboard/containers/DashboardTools/index.tsx
  src/main/resources/react4xp/dashboard/containers/Jobs/index.tsx
  src/main/resources/services/rssPush/rssPush.ts
  src/main/resources/services/rssPush/rssPush.xml
  src/main/resources/site/i18n/phrases.properties
  src/main/resources/site/i18n/phrases_en.properties
  src/main/resources/site/i18n/phrases_nn.properties
  src/main/resources/site/pages/default/default.ts
  src/main/resources/tasks/banVarnishPageCache/banVarnishPageCache.ts
  src/main/resources/tasks/pushRssNews/pushRssNews.ts
  src/main/resources/tasks/pushRssNews/pushRssNews.xml
  src/main/resources/tasks/pushRssStatkal/pushRssStatkal.ts
  src/main/resources/tasks/pushRssStatkal/pushRssStatkal.xml
  src/main/resources/tasks/updateCalculator/updateCalculator.ts
  src/main/resources/tasks/updateFrontpageKeyfigures/updateFrontpageKeyfigures.ts
  src/main/resources/tasks/updateFrontpageKeyfigures/updateFrontpageKeyfigures.xml
  src/main/resources/tasks/updateSDDSTables/updateSDDSTables.ts
Labels: minor-release

#3292 Prodløft
  .husky/pre-push
  gradle.properties
  src/main/resources/lib/ssb/cache/partCache.ts
  src/main/resources/site/macros/simpleStatbank/simpleStatbank.ts
  src/main/resources/site/parts/simpleStatbank/simpleStatbank.ts
Labels: patch-release

#3312 Prodløft
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/jira_issue_title.yaml
  .github/workflows/release-please.yaml
  gradle.properties
  release-please-config.json
  src/main/resources/assets/styles/_cookieBanner.scss
  src/main/resources/assets/styles/_footer.scss
  src/main/resources/assets/styles/_timeline.scss
  src/main/resources/index.d.ts
  src/main/resources/lib/ssb/parts/footer.ts
  src/main/resources/lib/types/footer.ts
  src/main/resources/lib/types/partTypes/article.ts
  src/main/resources/react4xp/_entries/CookieBanner.tsx
  src/main/resources/react4xp/_entries/Footer.tsx
  src/main/resources/site/i18n/phrases.properties
  src/main/resources/site/i18n/phrases_en.properties
  src/main/resources/site/i18n/phrases_nn.properties
  src/main/resources/site/pages/default/default.html
  src/main/resources/site/pages/default/default.ts
  src/main/resources/site/parts/article/article.ts
  src/main/resources/site/parts/article/article.tsx
  src/main/resources/site/parts/cookieBannerResetButton/cookieBannerResetButton.ts
  src/main/resources/site/parts/cookieBannerResetButton/cookieBannerResetButton.tsx
  src/main/resources/site/parts/cookieBannerResetButton/cookieBannerResetButton.xml
  src/main/resources/site/parts/timeline/timeline.tsx
Labels: minor-release

#3049 MIM-2082 add backticks quotemarks 2
  src/main/resources/lib/ssb/utils/nameSearchUtils.ts
  src/main/resources/site/parts/nameSearch/nameSearch.jsx
Labels: nais
